services:
  mariadb:
    image: mariadb:11
    container_name: rsai-click-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rsai_click_pwd
      MARIADB_DATABASE: rsai_click
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: rsai-click-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
