/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin/pages/$pageId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/pages': typeof AdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/register'
    | '/admin/'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug'
    | '/login'
    | '/register'
    | '/admin/'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
